//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationA
{
    using System;
    using System.Collections.Generic;
    
    public partial class checks
    {
        public int id { get; set; }
        public int number { get; set; }
        public string concept { get; set; }
        public int client_id { get; set; }
        public System.DateTime payment_date { get; set; }
        public decimal amount { get; set; }
        public string amount_in_letters { get; set; }
        public int invoice_id { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual invoices invoices { get; set; }
    }
}
